version: '3.8'
services:
  gradle-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: gradle-app
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom
