@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Create Formation

autonumber

actor Organization
participant ":FormationCreationUI" as ui_creation
participant ":FormationCreationController" as ctrl_creation
participant "System" as system

activate Organization

    Organization -> ui_creation : navigates to Create Formation section
    activate ui_creation
        ui_creation -> ctrl_creation : displayFormationCreationForm()
        activate ctrl_creation
            ctrl_creation -> ui_creation : displayFormationCreationForm()
        deactivate ctrl_creation
    deactivate ui_creation

    Organization -> ui_creation : fills out formation creation form
    activate ui_creation
        ui_creation -> ctrl_creation : submitFormationCreationForm(formationDetails)
        activate ctrl_creation
            ctrl_creation -> system : submitFormationForReview(formationDetails)
            activate system
                system --> ctrl_creation : formationSubmittedConfirmation
            deactivate system
            ctrl_creation -> ui_creation : displayConfirmationMessage(formationSubmittedConfirmation)
        deactivate ctrl_creation
    deactivate ui_creation

deactivate Organization

@enduml
