@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Apply to Mentorship

autonumber

actor RegisteredRefugee
participant ":MentorProfileUI" as ui_profile
participant ":MentorProfileController" as ctrl_profile
participant "System" as system

activate RegisteredRefugee

    RegisteredRefugee -> ui_profile : views available mentors
    activate ui_profile
        ui_profile -> ctrl_profile : loadMentorProfiles()
        activate ctrl_profile
            ctrl_profile -> system : getAvailableMentors()
            activate system
                system --> ctrl_profile : availableMentorsList
            deactivate system
            ctrl_profile -> ui_profile : displayMentorProfiles(availableMentorsList)
        deactivate ctrl_profile
    deactivate ui_profile

    RegisteredRefugee -> ui_profile : selects a mentor profile
    activate ui_profile
        ui_profile -> ctrl_profile : viewMentorProfile(selectedMentor)
        activate ctrl_profile
            ctrl_profile -> ui_profile : displayMentorProfileDetails(selectedMentor)
        deactivate ctrl_profile
    deactivate ui_profile

    RegisteredRefugee -> system : apply for mentorship
    activate system
        system -> RegisteredRefugee : provideMentorshipApplicationForm(selectedMentor)
    deactivate system

deactivate RegisteredRefugee

@enduml
