@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Create Organizations Sequence Diagram

autonumber

actor SystemAdministrator
participant "RefugeeLink Admin Panel" as admin_panel
participant "Organization Creation Form" as creation_form
participant "RefugeeLink Administrator Ctrl" as platform_admin

activate SystemAdministrator

SystemAdministrator -> admin_panel : Accesses RefugeeLink Admin Panel
activate admin_panel
    admin_panel -> SystemAdministrator : Displays Organization Creation Feature
    SystemAdministrator -> admin_panel : Opens Organization Creation Feature
    admin_panel -> creation_form : Displays Organization Creation Form
    activate creation_form
        creation_form -> admin_panel : Submits Organization Details
        admin_panel -> platform_admin : Submits Organization Details for Review
    deactivate creation_form
    admin_panel -> SystemAdministrator : Displays Confirmation Message
deactivate admin_panel

activate platform_admin
    platform_admin -> platform_admin : Reviews Organization Details
    platform_admin -> admin_panel : Approves Organization
    admin_panel -> SystemAdministrator : Sends Approval Notification
deactivate platform_admin

deactivate SystemAdministrator
@enduml
