@startuml
autonumber

Guest -> RegistrationRefugeePage: Accesses Registration Page
RegistrationRefugeePage -> RegistrationController: Submits Registration Form
RegistrationController -> Database: Store Registration Data
Database --> RegistrationController: Confirmation
RegistrationController --> Guest: Confirmation Message

@enduml
