@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Refugee Registration Process

autonumber

actor Guest
participant "RegistrationRefugeePage" as RegPage
participant "RegistrationController" as RegCtrl
participant Database

activate Guest

Guest -> RegPage : Accesses Registration Page
activate RegPage

RegPage -> RegCtrl : Submits Registration Form
activate RegCtrl

RegCtrl -> Database : Store Registration Data
activate Database
Database --> RegCtrl : Confirmation
deactivate Database

RegCtrl --> Guest : Confirmation Message
deactivate RegCtrl
deactivate RegPage

deactivate Guest

@enduml
