@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title View News about Refugees on Homepage

autonumber

actor Guest
participant ":HomepageUI" as ui
participant ":HomepageController" as ctrl
participant "NewsRepository" as newsRepo
participant "System" as system

activate Guest

    Guest -> ui : accesses homepage
    activate ui
        ui -> ctrl : loadNews()
        activate ctrl
            ctrl -> newsRepo : getLatestNews()
            activate newsRepo
                newsRepo -> newsRepo : fetchNews()
                newsRepo --> ctrl : newsList
            deactivate newsRepo
            ctrl -> system : displayNews(newsList)
            activate system
                system --> ctrl : newsDisplayedConfirmation
            deactivate system
            ctrl -> ui : showNews(newsList)
        deactivate ctrl
    deactivate ui

deactivate Guest

@enduml
