package pt.upskill.RefugeeLINK.Enums;

public enum Profession {
    ENGINEER("Engineer"),
    DOCTOR("Doctor"),
    TEACHER("Teacher"),
    ARTIST("Artist"),
    LAWYER("Lawyer"),
    CHEF("Chef"),
    SOFTWARE_DEVELOPER("Software Developer"),
    ENTREPRENEUR("Entrepreneur"),
    WRITER("Writer"),
    MUSICIAN("Musician"),
    NURSE("Nurse"),
    ARCHITECT("Architect"),
    ACCOUNTANT("Accountant"),
    POLICE_OFFICER("Police Officer"),
    FIREFIGHTER("Firefighter"),
    DENTIST("Dentist"),
    PHARMACIST("Pharmacist"),
    PSYCHOLOGIST("Psychologist"),
    ELECTRICIAN("Electrician"),
    PLUMBER("Plumber"),
    MECHANIC("Mechanic"),
    PILOT("Pilot"),
    FARMER("Farmer"),
    JOURNALIST("Journalist"),
    GRAPHIC_DESIGNER("Graphic Designer"),
    MARKETING_MANAGER("Marketing Manager"),
    PHYSIOTHERAPIST("Physiotherapist"),
    REAL_ESTATE_AGENT("Real Estate Agent"),
    BARISTA("Barista"),
    FITNESS_TRAINER("Fitness Trainer"),
    FLIGHT_ATTENDANT("Flight Attendant"),
    ACTOR("Actor"),
    BANKER("Banker"),
    LIBRARIAN("Librarian"),
    MILITARY_OFFICER("Military Officer"),
    PARAMEDIC("Paramedic"),
    SOCIAL_WORKER("Social Worker"),
    VETERINARIAN("Veterinarian"),
    HAIRDRESSER("Hairdresser"),
    TAXI_DRIVER("Taxi Driver"),
    WAITER("Waiter"),
    TOUR_GUIDE("Tour Guide"),
    SCIENTIST("Scientist"),
    CONSULTANT("Consultant"),
    PHOTOGRAPHER("Photographer"),
    IT_TECHNICIAN("IT Technician"),
    EVENT_PLANNER("Event Planner"),
    SECRETARY("Secretary"),
    CARPENTER("Carpenter"),
    ACTUARY("Actuary"),
    ASTROLOGER("Astrologer"),
    BREWER("Brewer"),
    CHIROPRACTOR("Chiropractor"),
    DIETITIAN("Dietitian"),
    GEOLOGIST("Geologist"),
    HISTORIAN("Historian"),
    JUDGE("Judge"),
    LIFEGUARD("Lifeguard"),
    MORTICIAN("Mortician"),
    NOTARY("Notary"),
    OPTOMETRIST("Optometrist"),
    PARALEGAL("Paralegal"),
    RADAR_CONTROLLER("Radar Controller"),
    ZOOKEEPER("Zookeeper"),
    UNDERWATER_WELDER("Underwater Welder"),
    BANK_TELLER("Bank Teller"),
    BEAUTICIAN("Beautician"),
    BREWMASTER("Brewmaster"),
    CARTOGRAPHER("Cartographer"),
    CHOREOGRAPHER("Choreographer"),
    COMPOSER("Composer"),
    COMPUTER_PROGRAMMER("Computer Programmer"),
    COUNSELOR("Counselor"),
    CRIMINAL_INVESTIGATOR("Criminal Investigator"),
    CRIMINOLOGIST("Criminologist"),
    DATA_ANALYST("Data Analyst"),
    DATABASE_ADMINISTRATOR("Database Administrator"),
    DEMONOLOGIST("Demonologist"),
    ECONOMIST("Economist"),
    EDITOR("Editor"),
    EMBALMER("Embalmer"),
    ETHNOLOGIST("Ethnologist"),
    FORENSIC_SCIENTIST("Forensic Scientist"),
    GAMER("Gamer"),
    GARDENER("Gardener"),
    GEMOLOGIST("Gemologist"),
    GENETICIST("Geneticist"),
    GLASSBLOWER("Glassblower"),
    HAIRSTYLIST("Hairstylist"),
    HOME_INSPECTOR("Home Inspector"),
    HORSE_TRAINER("Horse Trainer"),
    INTERIOR_DESIGNER("Interior Designer"),
    JEWELER("Jeweler"),
    LINGUIST("Linguist"),
    MAGISTRATE("Magistrate"),
    MAKEUP_ARTIST("Makeup Artist"),
    MARINE_BIOLOGIST("Marine Biologist"),
    MEDICAL_TRANSCRIPTIONIST("Medical Transcriptionist"),
    METEOROLOGIST("Meteorologist"),
    MICROBIOLOGIST("Microbiologist"),
    MUSEUM_CURATOR("Museum Curator"),
    MYCOLOGIST("Mycologist"),
    NUCLEAR_PHYSICIST("Nuclear Physicist"),
    NUMISMATIST("Numismatist"),
    OCEANOGRAPHER("Oceanographer"),
    ORNITHOLOGIST("Ornithologist"),
    PARASITOLOGIST("Parasitologist"),
    PATHOLOGIST("Pathologist"),
    PALEONTOLOGIST("Paleontologist"),
    PEACE_OFFICER("Peace Officer"),
    PENNY_STOCK_TRADER("Penny Stock Trader"),
    PERFORMING_ARTIST("Performing Artist"),
    PETROLEUM_ENGINEER("Petroleum Engineer"),
    PHLEBOTOMIST("Phlebotomist"),
    PHOTOJOURNALIST("Photojournalist"),
    PHYSICIAN_ASSISTANT("Physician Assistant"),
    POLITICAL_SCIENTIST("Political Scientist"),
    POSTMASTER("Postmaster"),
    PSYCHIATRIST("Psychiatrist"),
    PUBLIC_RELATIONS_SPECIALIST("Public Relations Specialist"),
    QUANTUM_PHYSICIST("Quantum Physicist"),
    RADIATION_THERAPIST("Radiation Therapist"),
    RADIOLOGIST("Radiologist"),
    SEISMOLOGIST("Seismologist"),
    SHEET_METAL_WORKER("Sheet Metal Worker"),
    SOLAR_ENGINEER("Solar Engineer"),
    STATISTICIAN("Statistician"),
    TAXIDERMIST("Taxidermist"),
    TATTOO_ARTIST("Tattoo Artist"),
    TELECOMMUNICATIONS_TECHNICIAN("Telecommunications Technician"),
    URBAN_PLANNER("Urban Planner"),
    VIROLOGIST("Virologist"),
    VOLCANOLOGIST("Volcanologist"),
    WILDLIFE_BIOLOGIST("Wildlife Biologist"),
    WIND_TURBINE_TECHNICIAN("Wind Turbine Technician"),
    OTHER("Other");

    private final String name;

    Profession(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}

