@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Chat with Apprentices Sequence Diagram

autonumber

actor Mentor
participant "RefugeeLink App" as app
participant "Chat Feature" as chat
participant "Apprentice" as apprentice

activate Mentor

Mentor -> app : Opens RefugeeLink App
activate app
    app -> chat : Accesses Chat Feature
    activate chat
        chat -> app : Display List of Apprentices
        app -> chat : Shows List of Apprentices
        chat -> app : Selects an Apprentice
        app -> chat : Initiates Chat Session
        chat -> app : Displays Chat Interface
    deactivate chat
deactivate app

Mentor -> chat : Sends Message
activate chat
    chat -> apprentice : Sends Message
    activate apprentice
        apprentice -> chat : Receives Message
    deactivate apprentice
    chat -> Mentor : Confirms Message Sent
deactivate chat

deactivate Mentor
@enduml
