@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) for Viewing News about Refugees on Homepage

autonumber

actor Guest
participant ":System" as System

activate Guest
    Guest -> System : accesses the homepage of the system
activate System
    System -> Guest : displays news articles and updates related to refugees
deactivate System

activate Guest
    Guest -> System : views headlines and summaries of the news items
deactivate Guest


@enduml
