@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title View Available Mentors

autonumber

actor RegisteredRefugee
participant ":MentorSectionUI" as ui
participant ":MentorSectionController" as ctrl
participant "MentorRepository" as mentorRepo
participant "System" as system

activate RegisteredRefugee

    RegisteredRefugee -> ui : navigates to mentor section
    activate ui
        ui -> ctrl : loadAvailableMentors()
        activate ctrl
            ctrl -> mentorRepo : getAvailableMentors()
            activate mentorRepo
                mentorRepo -> mentorRepo : fetchAvailableMentors()
                mentorRepo --> ctrl : mentorList
            deactivate mentorRepo
            ctrl -> system : displayMentors(mentorList)
            activate system
                system --> ctrl : mentorsDisplayedConfirmation
            deactivate system
            ctrl -> ui : showMentors(mentorList)
        deactivate ctrl
    deactivate ui

deactivate RegisteredRefugee

@enduml
